# For now, to ease development, this config acts as the dev build. Eventually
# it will be renamed to docker-compose-dev.yaml, and docker-compose.yaml will
# be in place for non-dev builds.

version: '3.9'

services:
  api:
    build: ./src/api
    command: npm run dev:docker
    environment:
      - API_PORT=${API_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_ACCOUNT_NUMBER=${AWS_ACCOUNT_NUMBER}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_QUEUE_NAME=${AWS_QUEUE_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./src/api/:/code
      # NOTE: Below exclusion for API may not be needed, but including for consistency since 'web' includes it.
      # Exclude host's node_modules for container and processor architecture compatibility.
      - /code/node_modules/
  web:
    build: ./src/web
    command: npm run dev:docker
    depends_on:
      - api
    environment:
      - VITE_API_PORT=${VITE_API_PORT}
      - WEB_PORT=${WEB_PORT}
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    volumes:
      - ./src/web/:/code
      # Exclude host's node_modules for container and processor architecture compatibility.
      - /code/node_modules/